# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKoiVebpYki2ctq8FXtBzGhtfKGMixSe
"""

import pandas as pd
import yfinance as yf
import numpy as num
url='/content/MVR.csv'
df=pd.read_csv(url)
print(df)
mean_value=df['Open_M'].mean()
print(f"mean value:-{mean_value}")
median_value=df['Open_M'].median()
print(f"median value:-{median_value}")
mode_value=df['Open_M'].mode()
print(f"mode value:-{mode_value}")
var_value=df['Open_M'].var()
print(f"variable value:-{var_value}")
std_value=df['Open_M'].std()
print(f"standard deviation value:-{std_value}")
plt.xlabel('Open_M')
plt.ylabel('Count')
plt.show()

from google.colab import drive
drive.mount('/content/drive')